import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>TopTen Agro</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;
